### ISSUE TITLE
Build "fails" if there are no changes

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-data#31]
There's no need for it to fail I don't think. So we need to add a check for no changes and don't bother pushing if there aren't any. I'm not sure why `git` would exit 1 for no changes.

Need to be careful that we don't ignore real errors, so no `|| exit 0` stuff.

This doesn't affect the deployed site so it's not as urgent as it looks. I've disabled CRON in the meantime.

**Comment by Norric1Admin** [comment]
For now, we get around this by adding/removing a newline in the Readme.md

**Comment by dougmet** [comment]
I'm trying to adjust deploy so it appends the time stamp to the README just before deploying. This should mean it's always different.

**Comment by dougmet** [comment]
Looks like that worked. Monitor when live deployments happen and reopen if there's a problem.

**Comment by Norric1Admin** [comment]
Good fix. We'll keep an eye on the next push to live.
